import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Progress } from "@/components/ui/progress";
import { ScrollArea } from "@/components/ui/scroll-area";
import { 
  Download, 
  Calendar, 
  TrendingUp, 
  Clock, 
  Target,
  Brain,
  Heart,
  Share2,
  FileText
} from "lucide-react";
import { cn } from "@/lib/utils";

interface SessionLog {
  id: string;
  date: string;
  module: string;
  duration: number; // minutes
  score?: number;
  notes?: string;
  domain: string;
}

interface CaregiverViewProps {
  patientName?: string;
  domainProgress: Record<string, number>;
  sessionLogs: SessionLog[];
  onExport?: () => void;
  className?: string;
}

const domainLabels: Record<string, { name: string; color: string }> = {
  attention: { name: 'Attention', color: '#f97316' },
  memory: { name: 'Memory', color: '#8b5cf6' },
  executive: { name: 'Executive', color: '#06b6d4' },
  communication: { name: 'Communication', color: '#10b981' },
  social: { name: 'Social', color: '#ec4899' },
  pta: { name: 'PTA', color: '#eab308' },
};

export const CaregiverView = ({
  patientName = "Patient",
  domainProgress,
  sessionLogs,
  onExport,
  className,
}: CaregiverViewProps) => {
  const [selectedPeriod, setSelectedPeriod] = useState<'week' | 'month' | 'all'>('week');

  // Calculate stats
  const totalSessions = sessionLogs.length;
  const totalMinutes = sessionLogs.reduce((sum, log) => sum + log.duration, 0);
  const avgScore = sessionLogs.filter(l => l.score).length > 0
    ? Math.round(sessionLogs.filter(l => l.score).reduce((sum, l) => sum + (l.score || 0), 0) / sessionLogs.filter(l => l.score).length)
    : 0;
  
  const overallProgress = Object.values(domainProgress).length > 0
    ? Math.round(Object.values(domainProgress).reduce((a, b) => a + b, 0) / Object.values(domainProgress).length)
    : 0;

  // Filter logs by period
  const filteredLogs = sessionLogs.filter(log => {
    const logDate = new Date(log.date);
    const now = new Date();
    if (selectedPeriod === 'week') {
      const weekAgo = new Date(now.setDate(now.getDate() - 7));
      return logDate >= weekAgo;
    }
    if (selectedPeriod === 'month') {
      const monthAgo = new Date(now.setMonth(now.getMonth() - 1));
      return logDate >= monthAgo;
    }
    return true;
  });

  const generateReport = () => {
    const report = `
INCOG 2.0 COGNITIVE REHABILITATION REPORT
==========================================
Patient: ${patientName}
Generated: ${new Date().toLocaleDateString()}
Period: ${selectedPeriod === 'all' ? 'All Time' : selectedPeriod === 'week' ? 'Past Week' : 'Past Month'}

OVERALL PROGRESS: ${overallProgress}%

DOMAIN BREAKDOWN:
${Object.entries(domainProgress).map(([domain, progress]) => 
  `  ${domainLabels[domain]?.name || domain}: ${progress}%`
).join('\n')}

SESSION SUMMARY:
  Total Sessions: ${totalSessions}
  Total Time: ${Math.round(totalMinutes / 60)} hours ${totalMinutes % 60} minutes
  Average Score: ${avgScore}%

RECENT SESSIONS:
${filteredLogs.slice(0, 10).map(log => 
  `  ${log.date} - ${log.module} (${log.duration}min)${log.score ? ` Score: ${log.score}%` : ''}${log.notes ? `\n    Notes: ${log.notes}` : ''}`
).join('\n')}

CLINICAL NOTES:
  - Evidence-based interventions per INCOG 2.0 guidelines
  - All modules aligned with Level A/B recommendations
  - Reference: PMID 36594858

==========================================
Generated by Phoenix Recovery Platform
    `.trim();

    const blob = new Blob([report], { type: 'text/plain' });
    const url = window.URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `INCOG_Report_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    window.URL.revokeObjectURL(url);
    
    onExport?.();
  };

  return (
    <Card className={cn("bg-slate-900/80 border-orange-500/20", className)}>
      <CardHeader className="pb-3">
        <div className="flex items-center justify-between">
          <CardTitle className="text-lg text-orange-100 flex items-center gap-2">
            <FileText className="w-5 h-5 text-orange-400" />
            Caregiver / Clinician View
          </CardTitle>
          <div className="flex gap-2">
            <Button
              variant="outline"
              size="sm"
              className="text-xs border-orange-500/30 text-orange-300"
              onClick={generateReport}
            >
              <Download className="w-3 h-3 mr-1" />
              Export Report
            </Button>
          </div>
        </div>
      </CardHeader>
      
      <CardContent className="space-y-4">
        {/* Period Selector */}
        <div className="flex gap-2">
          {(['week', 'month', 'all'] as const).map((period) => (
            <Button
              key={period}
              variant={selectedPeriod === period ? "default" : "ghost"}
              size="sm"
              className={cn(
                "text-xs",
                selectedPeriod === period 
                  ? "bg-orange-500 text-white" 
                  : "text-orange-300"
              )}
              onClick={() => setSelectedPeriod(period)}
            >
              {period === 'week' ? 'Week' : period === 'month' ? 'Month' : 'All Time'}
            </Button>
          ))}
        </div>

        {/* Quick Stats */}
        <div className="grid grid-cols-4 gap-2">
          <div className="bg-white/5 rounded-lg p-3 text-center">
            <TrendingUp className="w-4 h-4 mx-auto text-emerald-400 mb-1" />
            <div className="text-lg font-bold text-white">{overallProgress}%</div>
            <div className="text-xs text-gray-400">Progress</div>
          </div>
          <div className="bg-white/5 rounded-lg p-3 text-center">
            <Target className="w-4 h-4 mx-auto text-orange-400 mb-1" />
            <div className="text-lg font-bold text-white">{totalSessions}</div>
            <div className="text-xs text-gray-400">Sessions</div>
          </div>
          <div className="bg-white/5 rounded-lg p-3 text-center">
            <Clock className="w-4 h-4 mx-auto text-cyan-400 mb-1" />
            <div className="text-lg font-bold text-white">{Math.round(totalMinutes / 60)}h</div>
            <div className="text-xs text-gray-400">Total Time</div>
          </div>
          <div className="bg-white/5 rounded-lg p-3 text-center">
            <Brain className="w-4 h-4 mx-auto text-purple-400 mb-1" />
            <div className="text-lg font-bold text-white">{avgScore}%</div>
            <div className="text-xs text-gray-400">Avg Score</div>
          </div>
        </div>

        {/* Domain Progress */}
        <div className="space-y-2">
          <h4 className="text-sm font-medium text-orange-200">Domain Progress</h4>
          {Object.entries(domainProgress).map(([domain, progress]) => (
            <div key={domain} className="space-y-1">
              <div className="flex justify-between text-xs">
                <span style={{ color: domainLabels[domain]?.color }}>
                  {domainLabels[domain]?.name || domain}
                </span>
                <span className="text-gray-400">{progress}%</span>
              </div>
              <Progress 
                value={progress} 
                className="h-1.5"
                style={{ 
                  '--progress-color': domainLabels[domain]?.color 
                } as React.CSSProperties}
              />
            </div>
          ))}
        </div>

        {/* Session Log */}
        <div className="space-y-2">
          <h4 className="text-sm font-medium text-orange-200">Recent Sessions</h4>
          <ScrollArea className="h-[150px]">
            <div className="space-y-2">
              {filteredLogs.length === 0 ? (
                <p className="text-xs text-gray-500 text-center py-4">
                  No sessions recorded for this period
                </p>
              ) : (
                filteredLogs.slice(0, 10).map((log) => (
                  <div 
                    key={log.id}
                    className="flex items-center justify-between p-2 bg-white/5 rounded-lg"
                  >
                    <div className="flex items-center gap-2">
                      <div 
                        className="w-2 h-2 rounded-full"
                        style={{ backgroundColor: domainLabels[log.domain]?.color }}
                      />
                      <div>
                        <div className="text-sm text-white">{log.module}</div>
                        <div className="text-xs text-gray-400">{log.date}</div>
                      </div>
                    </div>
                    <div className="text-right">
                      <div className="text-sm text-white">{log.duration} min</div>
                      {log.score && (
                        <div className="text-xs text-emerald-400">{log.score}%</div>
                      )}
                    </div>
                  </div>
                ))
              )}
            </div>
          </ScrollArea>
        </div>

        {/* INCOG Reference */}
        <div className="flex items-center justify-between pt-2 border-t border-white/10">
          <Badge variant="outline" className="text-xs border-green-500/50 text-green-400">
            INCOG 2.0 Aligned
          </Badge>
          <a 
            href="https://pubmed.ncbi.nlm.nih.gov/36594858/"
            target="_blank"
            rel="noopener noreferrer"
            className="text-xs text-orange-400 hover:text-orange-300"
          >
            PMID: 36594858
          </a>
        </div>
      </CardContent>
    </Card>
  );
};

export default CaregiverView;
