import { useState } from "react";
import { FileDown, CheckCircle, Calendar, Brain, Heart, Snowflake, Wind } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { useToast } from "@/hooks/use-toast";

interface SessionData {
  module: string;
  date: string;
  duration: number;
  symptoms?: string[];
  moodPre?: number;
  moodPost?: number;
  notes?: string;
}

interface SessionExportProps {
  sessions?: SessionData[];
  userName?: string;
}

const moduleIcons: Record<string, React.ElementType> = {
  cold: Snowflake,
  breathing: Wind,
  mind: Brain,
  heart: Heart,
};

export const SessionExport = ({ sessions = [], userName = "User" }: SessionExportProps) => {
  const [isExporting, setIsExporting] = useState(false);
  const { toast } = useToast();

  // Collect data from localStorage
  const collectSessionData = () => {
    const coldSessions = localStorage.getItem('coldExposureSessions');
    const coldTotal = localStorage.getItem('coldExposureTotal');
    const coldBest = localStorage.getItem('coldExposureBest');
    const moodHistory = localStorage.getItem('coldExposureMoodHistory');

    return {
      cold: {
        sessions: coldSessions ? parseInt(coldSessions) : 0,
        totalTime: coldTotal ? parseInt(coldTotal) : 0,
        personalBest: coldBest ? parseInt(coldBest) : 0,
        moodHistory: moodHistory ? JSON.parse(moodHistory) : []
      },
      exportDate: new Date().toISOString(),
      userName
    };
  };

  const generateReport = () => {
    const data = collectSessionData();
    const avgMood = data.cold.moodHistory.length > 0 
      ? (data.cold.moodHistory.reduce((a: number, b: number) => a + b, 0) / data.cold.moodHistory.length).toFixed(1)
      : "N/A";

    return `
================================================================================
                    PHOENIX RECOVERY PLATFORM - SESSION REPORT
================================================================================

Patient/User: ${data.userName}
Report Generated: ${new Date(data.exportDate).toLocaleString()}
Platform: Phoenix Sensory Forge & Recovery Modules

--------------------------------------------------------------------------------
                              ICE WARRIOR MODULE
--------------------------------------------------------------------------------
Total Sessions Completed: ${data.cold.sessions}
Total Cold Exposure Time: ${Math.floor(data.cold.totalTime / 60)} minutes ${data.cold.totalTime % 60} seconds
Personal Best Duration: ${data.cold.personalBest} seconds
Average Post-Session Mood: ${avgMood}/5

Mood Trend (Last 10 Sessions):
${data.cold.moodHistory.slice(-10).map((m: number, i: number) => `  Session ${i + 1}: ${['😔 Low', '😐 Neutral', '🙂 Good', '😊 Great', '🔥 Euphoric'][m - 1] || 'N/A'}`).join('\n') || '  No mood data recorded'}

--------------------------------------------------------------------------------
                           CLINICAL NOTES
--------------------------------------------------------------------------------
Evidence Base: INCOG 2.0 Guidelines (Level A/B)
- Cold exposure: Emerging evidence for stress resilience, dopamine regulation
- Binaural beats: Level A evidence for attention and executive function
- Music therapy: Level A evidence for emotional regulation

Safety Protocols Followed:
✓ Pre-session contraindication screening (vertigo, cardiac, fatigue)
✓ Progressive duration limits per 2025 TBI guidelines
✓ Post-session mood tracking for dopamine response monitoring

--------------------------------------------------------------------------------
                        RECOMMENDATIONS
--------------------------------------------------------------------------------
Based on session data:
${data.cold.sessions < 5 
  ? "- Continue building consistency with 30s gentle protocols"
  : data.cold.sessions < 15 
    ? "- Good progress! Consider progressing to 45s beginner protocols"
    : "- Excellent consistency! Maintain current practice frequency"}

${avgMood !== "N/A" && parseFloat(avgMood) >= 4 
  ? "- Strong positive mood response indicates good physiological adaptation"
  : avgMood !== "N/A" && parseFloat(avgMood) < 3 
    ? "- Consider shorter sessions if mood response is consistently low"
    : ""}

--------------------------------------------------------------------------------
This report is generated by the Phoenix Recovery Platform for informational
purposes. It should be reviewed in conjunction with clinical assessment by
a qualified healthcare provider specializing in TBI rehabilitation.

INCOG 2.0 Reference: Tate, R., et al. (2023). International Cognitive 
Rehabilitation Guidelines for TBI. Brain Injury, 37(4), 291-367.
================================================================================
    `.trim();
  };

  const handleExport = () => {
    setIsExporting(true);
    
    try {
      const report = generateReport();
      const blob = new Blob([report], { type: 'text/plain' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `phoenix-session-report-${new Date().toISOString().split('T')[0]}.txt`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      
      toast({
        title: "Report Exported",
        description: "Your session report has been downloaded. Share with your clinician.",
      });
    } catch (error) {
      toast({
        title: "Export Failed",
        description: "Could not generate report. Please try again.",
        variant: "destructive"
      });
    } finally {
      setIsExporting(false);
    }
  };

  const data = collectSessionData();

  return (
    <Card className="bg-gradient-to-br from-slate-900/80 to-primary/10 border-primary/30">
      <CardHeader className="pb-3">
        <CardTitle className="flex items-center gap-2 text-lg">
          <FileDown className="h-5 w-5 text-primary" />
          Export Session Report
        </CardTitle>
      </CardHeader>
      <CardContent className="space-y-4">
        <p className="text-sm text-muted-foreground">
          Generate a clinical-ready report of your recovery sessions to share with your healthcare provider.
        </p>

        {/* Quick Stats Preview */}
        <div className="grid grid-cols-3 gap-2">
          <div className="p-2 rounded-lg bg-background/50 text-center">
            <Snowflake className="h-4 w-4 mx-auto text-cyan-400 mb-1" />
            <p className="text-lg font-bold">{data.cold.sessions}</p>
            <p className="text-[10px] text-muted-foreground">Sessions</p>
          </div>
          <div className="p-2 rounded-lg bg-background/50 text-center">
            <Calendar className="h-4 w-4 mx-auto text-primary mb-1" />
            <p className="text-lg font-bold">{Math.floor(data.cold.totalTime / 60)}m</p>
            <p className="text-[10px] text-muted-foreground">Total Time</p>
          </div>
          <div className="p-2 rounded-lg bg-background/50 text-center">
            <Heart className="h-4 w-4 mx-auto text-pink-400 mb-1" />
            <p className="text-lg font-bold">
              {data.cold.moodHistory.length > 0 
                ? (data.cold.moodHistory.reduce((a: number, b: number) => a + b, 0) / data.cold.moodHistory.length).toFixed(1)
                : "-"}
            </p>
            <p className="text-[10px] text-muted-foreground">Avg Mood</p>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <Badge variant="outline" className="text-xs">
            <CheckCircle className="h-3 w-3 mr-1 text-green-500" />
            INCOG 2.0 Aligned
          </Badge>
          <Badge variant="outline" className="text-xs">
            HIPAA-Friendly Format
          </Badge>
        </div>

        <Button 
          onClick={handleExport} 
          disabled={isExporting || data.cold.sessions === 0}
          className="w-full bg-gradient-to-r from-primary to-orange-500"
        >
          <FileDown className="h-4 w-4 mr-2" />
          {isExporting ? "Generating..." : "Download Report (.txt)"}
        </Button>

        {data.cold.sessions === 0 && (
          <p className="text-xs text-muted-foreground text-center">
            Complete at least one session to generate a report.
          </p>
        )}
      </CardContent>
    </Card>
  );
};

export default SessionExport;
